### ISSUE TITLE
Feature request: periodically check calendar files - detect changes

### ISSUE THREAD

**Issue by lutischan-ferenc** [i-Cell-Mobilsoft-Open-Source/wdc-backend#15]
Check xml loading directory for changes (hourly). On changes reinit the WorkdayCache.

```
class FileData {
        private long size;
        private long lastModified;

        public FileData(long size, long lastModified) {
            this.size = size;
            this.lastModified = lastModified;
        }

        public boolean isChanged(FileData compareTo) {
            boolean timeModified = compareTo.lastModified != lastModified;
            boolean sizeModified = compareTo.size != size;
            return timeModified || sizeModified;
        }
    }
```
Create a new field in WorkdayCacheInitializer e.g.: 
```
private static Map<String, FileData> xmlFiles = new HashMap<>();
```
Whrere key = fileName

In checkChanges() method check for changes: delete, create or modify.
On changes: refresh xmlFiles map and reinit the WorkdayCache (clear and init).

Of course, this can cause problems in validity of responses (concurrency).

**Comment by magyari-adam** [comment]
This is already implemented in java.nio.WatchService

**Comment by lutischan-ferenc** [comment]
Yes, as we talked about it, but the request was differrent.
